# TheMealDB ingredient (lowercase) -> catalogue id, or None for a staple left out of the list.
S = None
MAP = {
 # staples: salt, water, spices and seasonings, raising agents, extracts, alcohol in small amounts
 'salt': S, 'sea salt': S, 'kosher salt': S, 'coarse salt': S, 'celery salt': S, 'water': S, 'warm water': S, 'cold water': S, 'boiling water': S,
 'black pepper': S, 'pepper': S, 'ground black pepper': S, 'baking powder': S, 'bicarbonate of soda': S, 'vanilla extract': S, 'vanilla': S,
 'vanilla pod': S, 'vanilla sugar': S, 'almond extract': S, 'almond essence': S, 'pink food colouring': S, 'rose water': S, 'orange blossom water': S,
 'allspice': S, 'ground allspice': S, 'cardamom': S, 'ground cardomom': S, 'cloves': S, 'clove': S, 'nutmeg': S, 'ground nutmeg': S, 'saffron': S,
 'bay leaf': S, 'bay leaves': S, 'cayenne pepper': S, 'chilli powder': S, 'chili powder': S, 'chilli flakes': S, 'red pepper flakes': S, 'red chilli flakes': S,
 'ground coriander': S, 'ground ginger': S, 'garlic powder': S, 'ground onion': S, 'garam masala': S, 'harissa spice': S, 'oregano': S, 'sage': S,
 'marjoram': S, 'summer savoury': S, 'fennel seeds': S, 'caraway seed': S, 'seeds': S, 'all-purpose seasoning': S, 'seasoning': S, 'jerk': S, 'sazon': S,
 'ground mahleb': S, 'achiote paste': S, 'tamarind paste': S, 'red pepper paste': S, 'sweet chilli sauce': S, 'tobasco sauce': S, 'red pepper sauce': S,
 'dried sorrel': S, 'pickle juice': S, 'sugar syrup': S, 'banana leaves': S, 'pandan leaves': S, 'chickpea flour': S, 'peach juice': S,
 'sake': S, 'mirin': S, 'brandy': S, 'dark rum': S, 'dark beer': S, 'ginger cordial': S,
 # vegetables
 'onion': 'onion', 'onions': 'onion', 'chopped onion': 'onion', 'red onions': 'red-onion', 'spring onions': 'green-onion', 'scallions': 'green-onion',
 'shallots': 'shallot', 'challots': 'shallot', 'garlic': 'garlic', 'garlic clove': 'garlic', 'ginger': 'ginger', 'ginger paste': 'ginger',
 'potatoes': 'potato', 'small potatoes': 'potato', 'new potatoes': 'potato', 'russet potato': 'potato', 'sweet potatoes': 'sweet-potato',
 'carrots': 'carrot', 'carrot': 'carrot', 'tomato': 'tomato', 'tomatoes': 'tomato', 'plum tomatoes': 'tomato', 'cherry tomatoes': 'cherry-tomato',
 'baby plum tomatoes': 'cherry-tomato', 'red pepper': 'pepper', 'green pepper': 'pepper', 'yellow pepper': 'pepper', 'roasted pepper': 'pepper',
 'red chilli': 'chili', 'green chilli': 'chili', 'scotch bonnet': 'chili', 'jalapeno': 'chili', 'chilli': 'chili', 'cucumber': 'cucumber',
 'celery': 'celery', 'cabbage': 'cabbage', 'red cabbage': 'cabbage', 'chinese leaf': 'cabbage', 'leek': 'leek', 'spinach': 'spinach', 'callaloo': 'spinach',
 'broccoli': 'broccoli', 'mushrooms': 'mushroom', 'oyster mushrooms': 'mushroom', 'courgettes': 'zucchini', 'zucchini': 'zucchini',
 'aubergine': 'eggplant', 'egg plants': 'eggplant', 'baby aubergine': 'eggplant', 'pumpkin': 'pumpkin', 'butternut squash': 'pumpkin', 'zapallo squash': 'pumpkin',
 'fennel': 'fennel', 'fennel bulb': 'fennel', 'green beans': 'green-beans', 'peas': 'frozen-peas', 'frozen peas': 'frozen-peas', 'sugar snap peas': 'frozen-peas',
 'sweetcorn': 'corn', 'corn on the cob': 'corn', 'beetroot': 'beetroot', 'beets': 'beetroot', 'radish': 'radish', 'lettuce': 'lettuce',
 'baby lettuce leaves': 'lettuce', 'rocket': 'rocket', 'bean sprouts': 'bean-sprouts', 'asparagus': 'asparagus', 'avocado': 'avocado',
 'breadfruit': 'breadfruit', 'yuca': 'cassava', 'raw yucca': 'cassava', 'cassava flour': 'cassava', 'taro': 'taro', 'green papaya': 'papaya', 'rhubarb': 'rhubarb',
 'vine leaves': 'vine-leaves', 'pickled grape leaves': 'vine-leaves', 'sauerkraut': 'sauerkraut', 'palm hearts': 'palm-hearts', 'capers': 'capers',
 # herbs
 'parsley': 'parsley', 'chopped parsley': 'parsley', 'coriander': 'coriander', 'cilantro': 'coriander', 'coriander leaves': 'coriander', 'mint': 'mint',
 'dried mint': 'mint', 'dill': 'dill', 'thyme': 'thyme', 'fresh thyme': 'thyme', 'rosemary': 'rosemary', 'basil': 'basil', 'basil leaves': 'basil',
 'fresh basil': 'basil', 'chives': 'chives', 'lemongrass': 'lemongrass',
 # fruit
 'lemon': 'lemon', 'lemons': 'lemon', 'lemon juice': 'lemon', 'lemon zest': 'lemon', 'lime': 'lime', 'lime juice': 'lime', 'orange': 'orange',
 'orange juice': 'orange', 'apples': 'apple', 'braeburn apples': 'apple', 'banana': 'banana', 'plantain': 'plantain', 'mango': 'mango',
 'pomegranate': 'pomegranate', 'strawberries': 'strawberry', 'raspberries': 'raspberries', 'blueberries': 'blueberries', 'blackberries': 'blackberries',
 'cherry': 'cherries', 'apricot': 'apricot', 'peaches': 'peach', 'longan': 'longan',
 # dairy (never staples: they decide the kashrut)
 'butter': 'butter', 'unsalted butter': 'butter', 'salted butter': 'butter', 'melted butter': 'butter', 'milk': 'milk', 'whole milk': 'milk', 'buttermilk': 'milk',
 'double cream': 'cream', 'heavy cream': 'cream', 'single cream': 'cream', 'whipping cream': 'cream', 'clotted cream': 'cream', 'creme fraiche': 'cream',
 'sour cream': 'sour-cream', 'full fat sour cream': 'sour-cream', 'greek yogurt': 'yogurt', 'yogurt': 'yogurt', 'natural yoghurt': 'yogurt',
 'cream cheese': 'white-cheese', 'mascarpone': 'white-cheese', 'sweet quark': 'white-cheese', 'farmers cheese': 'white-cheese', 'queso fresco': 'white-cheese',
 'cheese': 'cheese', 'cheddar cheese': 'cheese', 'gouda cheese': 'cheese', 'emmentaler cheese': 'cheese', 'brie': 'cheese', 'stilton cheese': 'cheese',
 'liquid cheese': 'cheese', 'goats cheese': 'cheese', 'feta': 'feta', 'mozzarella': 'mozzarella', 'mozzarella balls': 'mozzarella',
 'parmesan': 'parmesan', 'parmesan cheese': 'parmesan', 'condensed milk': 'condensed-milk', 'sweetened condensed milk': 'condensed-milk',
 'evaporated milk': 'condensed-milk', 'dulce de leche': 'dulce-de-leche', 'custard': 'custard', 'ice cream': 'ice-cream', 'milk chocolate': 'milk-chocolate',
 # eggs
 'eggs': 'egg', 'egg': 'egg', 'egg yolks': 'egg', 'egg white': 'egg',
 # meat (never staples)
 'chicken': 'chicken', 'chicken thighs': 'chicken', 'chicken wings': 'chicken', 'chicken legs': 'chicken', 'chicken breast': 'chicken-breast',
 'chicken breasts': 'chicken-breast', 'beef': 'beef', 'beef brisket': 'beef', 'flank steak': 'beef', 'sirloin steak tips': 'beef', 'oxtail': 'beef',
 'corned beef': 'beef', 'ground beef': 'ground-beef', 'minced beef': 'ground-beef', 'lamb': 'lamb', 'lamb leg': 'lamb', 'lamb shoulder': 'lamb',
 'lamb loin chops': 'lamb', 'lamb mince': 'lamb', 'lamb fat': 'lamb', 'goat meat': 'goat', 'chicken stock': 'chicken-stock',
 'chicken stock cube': 'chicken-stock', 'beef stock': 'meat-stock', 'lamb stock': 'meat-stock',
 # fish
 'salmon': 'salmon', 'smoked salmon': 'salmon', 'hot smoked flaked salmon': 'salmon', 'cod': 'white-fish', 'codfish bulljaw': 'white-fish',
 'haddock': 'white-fish', 'smoked haddock': 'white-fish', 'salt cod': 'white-fish', 'barramundi': 'white-fish', 'tuna': 'tuna', 'sardines': 'sardines',
 'pilchards': 'sardines', 'anchovy fillet': 'anchovies', 'fish stock': 'fish-stock',
 # grains, bread, pastry
 'flour': 'flour', 'all purpose flour': 'flour', 'plain flour': 'flour', 'self-raising flour': 'flour', 'strong white bread flour': 'flour',
 'strong white flour': 'flour', 'bread flour': 'flour', 'white flour': 'flour', 'wheat flour': 'flour', 'strong wholemeal flour': 'flour', 'farine': 'flour',
 'corn flour': 'cornstarch', 'cornstarch': 'cornstarch', 'potato starch': 'cornstarch', 'cornmeal': 'cornmeal', 'fine yellow cornmeal': 'cornmeal',
 'white cornmeal': 'cornmeal', 'yellow masarepa': 'cornmeal', 'grits': 'cornmeal', 'semolina': 'semolina', 'semolina flour': 'semolina',
 'rye flour': 'rye-flour', 'rye': 'rye-flour', 'rye grain': 'rye-flour', 'buckwheat': 'buckwheat', 'buckwheat flour': 'buckwheat', 'freekeh': 'freekeh',
 'tapioca': 'tapioca', 'sticky rice flour': 'rice', 'rice': 'rice', 'basmati rice': 'rice', 'paella rice': 'rice', 'sushi rice': 'rice',
 'glutinous rice': 'rice', 'rice noodles': 'noodles', 'egg noodles': 'noodles', 'spaghetti': 'pasta', 'macaroni': 'pasta', 'fettuccine': 'pasta',
 'farfalle': 'pasta', 'couscous': 'couscous', 'oats': 'oats', 'ground oats': 'oats', 'yeast': 'yeast', 'instant yeast': 'yeast',
 'fast action yeast': 'yeast', 'bread': 'bread', 'white bread': 'bread', 'stale bread': 'bread', 'baguette': 'bread', 'rye bread': 'bread',
 'english muffins': 'bread', 'pita bread': 'pita', 'breadcrumbs': 'breadcrumbs', 'puff pastry': 'puff-pastry', 'shortcrust pastry': 'shortcrust-pastry',
 'filo pastry': 'filo-pastry', 'phyllo dough': 'filo-pastry', 'digestive biscuits': 'biscuits', 'pretzels': 'pretzels',
 # pulses
 'chickpeas': 'chickpeas', 'lentils': 'lentils', 'brown lentils': 'lentils', 'kidney beans': 'kidney-beans', 'black beans': 'black-beans',
 'cannellini beans': 'white-beans', 'broad beans': 'broad-beans', 'mung bean paste': 'mung-beans',
 # pantry
 'sugar': 'sugar', 'caster sugar': 'sugar', 'brown sugar': 'sugar', 'icing sugar': 'sugar', 'granulated sugar': 'sugar', 'muscovado sugar': 'sugar',
 'powdered sugar': 'sugar', 'golden caster sugar': 'sugar', 'dark brown soft sugar': 'sugar', 'ground sugar': 'sugar', 'honey': 'honey', 'clear honey': 'honey',
 'golden syrup': 'golden-syrup', 'black treacle': 'golden-syrup', 'molasses': 'golden-syrup', 'dutch stroop': 'golden-syrup', 'maple syrup': 'maple-syrup',
 'jam': 'jam', 'raspberry jam': 'jam', 'apricot jam': 'jam', 'sorrel jam': 'jam', 'olive oil': 'olive-oil', 'extra virgin olive oil': 'olive-oil',
 'vegetable oil': 'oil', 'sunflower oil': 'oil', 'canola oil': 'oil', 'rapeseed oil': 'oil', 'ground nut oil': 'oil', 'oil': 'oil', 'shortening': 'oil',
 'sesame seed oil': 'sesame-oil', 'coconut milk': 'coconut-milk', 'coconut cream': 'coconut-milk', 'vegetable stock': 'stock',
 'vegetable stock cube': 'stock', 'soy sauce': 'soy-sauce', 'red wine vinegar': 'vinegar', 'white wine vinegar': 'vinegar', 'apple cider vinegar': 'vinegar',
 'cider vinegar': 'vinegar', 'sherry vinegar': 'vinegar', 'balsamic vinegar': 'vinegar', 'rice vinegar': 'vinegar', 'white vinegar': 'vinegar',
 'mustard': 'mustard', 'dijon mustard': 'mustard', 'english mustard': 'mustard', 'mayonnaise': 'mayonnaise', 'tomato ketchup': 'ketchup',
 'tomato puree': 'tomato-paste', 'tomato sauce': 'canned-tomatoes', 'passata': 'canned-tomatoes', 'chopped tomatoes': 'canned-tomatoes',
 'tinned tomatos': 'canned-tomatoes', 'green olives': 'olives', 'black olives': 'olives', 'tahini': 'tahini', 'tahini paste': 'tahini',
 'thai red curry paste': 'curry', 'curry powder': 'curry', 'cumin': 'cumin', 'ground cumin': 'cumin', 'cumin seeds': 'cumin', 'paprika': 'paprika',
 'smoked paprika': 'paprika', 'cinnamon': 'cinnamon', 'ground cinnamon': 'cinnamon', 'cinnamon stick': 'cinnamon', 'turmeric': 'turmeric',
 'turmeric powder': 'turmeric', 'dark chocolate': 'chocolate', 'plain chocolate': 'chocolate', 'chocolate chips': 'chocolate', 'cacao': 'cocoa',
 'cocoa powder': 'cocoa', 'unsweetened cocoa': 'cocoa', 'almonds': 'almonds', 'ground almonds': 'almonds', 'almond flour': 'almonds',
 'walnuts': 'walnuts', 'ground walnuts': 'walnuts', 'pine nuts': 'pine-nuts', 'pistachio': 'pistachios', 'peanuts': 'peanuts', 'roasted peanut': 'peanuts',
 'unsalted peanuts': 'peanuts', 'peanut butter': 'peanut-butter', 'hazlenuts': 'hazelnuts', 'cashew nuts': 'cashews', 'pecan nuts': 'pecans',
 'coconut': 'coconut', 'desiccated coconut': 'coconut', 'shredded coconut': 'coconut', 'coconut flakes': 'coconut', 'sesame seed': 'sesame',
 'poppy seeds': 'poppy-seeds', 'raisins': 'raisins', 'light raisins': 'raisins', 'currants': 'raisins', 'dried apricots': 'dried-apricots',
 'prunes': 'prunes', 'dried fruit': 'dried-fruit', 'mixed peel': 'dried-fruit', 'fruit mix': 'dried-fruit', 'glace cherry': 'dried-fruit',
 'marzipan': 'marzipan', 'alinos sauce': S, 'demerara sugar': 'sugar', 'gruyere': 'cheese', 'sea bass fillets': 'white-fish', 'sultanas': 'raisins', 'ricotta': 'white-cheese', 'vine tomatoes': 'tomato', 'red wine': 'wine', 'white wine': 'wine', 'dry white wine': 'wine', 'dry sherry': 'wine', 'sweet sherry': 'wine',
}
