# id: (fr, en, he, category, kashrut or None, shelfDays, keywords)
NEW = {
 'lime': ('Citron vert', 'Lime', 'ליים', 'fruit', None, 14, ['citron vert', 'lime', 'ליים']),
 'cornstarch': ('Fécule de maïs', 'Cornflour', 'קורנפלור', 'grocery', None, 365, ['maizena', 'fecule de mais', 'cornflour', 'cornstarch', 'קורנפלור']),
 'yeast': ('Levure de boulanger', 'Yeast', 'שמרים', 'grocery', None, 120, ['levure de boulanger', 'levure seche', 'yeast', 'שמרים']),
 'sour-cream': ('Crème aigre', 'Sour cream', 'שמנת חמוצה', 'dairy', 'dairy', 14, ['creme aigre', 'sour cream', 'שמנת חמוצה']),
 'condensed-milk': ('Lait concentré', 'Condensed milk', 'חלב מרוכז', 'grocery', 'dairy', 365, ['lait concentre', 'condensed milk', 'evaporated milk', 'חלב מרוכז']),
 'dulce-de-leche': ('Confiture de lait', 'Dulce de leche', 'ריבת חלב', 'grocery', 'dairy', 180, ['confiture de lait', 'dulce de leche', 'ריבת חלב']),
 'custard': ('Crème anglaise', 'Custard', 'רפרפת', 'dairy', 'dairy', 5, ['creme anglaise', 'custard', 'רפרפת']),
 'ice-cream': ('Glace', 'Ice cream', 'גלידה', 'dairy', 'dairy', 90, ['glace vanille', 'creme glacee', 'ice cream', 'גלידה']),
 'milk-chocolate': ('Chocolat au lait', 'Milk chocolate', 'שוקולד חלב', 'grocery', 'dairy', 180, ['chocolat au lait', 'milk chocolate', 'שוקולד חלב']),
 'chicken-stock': ('Bouillon de volaille', 'Chicken stock', 'ציר עוף', 'grocery', 'meat', 365, ['bouillon de volaille', 'bouillon de poulet', 'chicken stock', 'ציר עוף', 'מרק עוף']),
 'meat-stock': ('Bouillon de viande', 'Beef stock', 'ציר בקר', 'grocery', 'meat', 365, ['bouillon de boeuf', 'bouillon de viande', 'beef stock', 'ציר בקר']),
 'fish-stock': ('Fumet de poisson', 'Fish stock', 'ציר דגים', 'grocery', None, 365, ['fumet de poisson', 'fish stock', 'ציר דגים']),
 'lamb': ('Agneau', 'Lamb', 'כבש', 'meat', 'meat', 4, ['agneau', 'lamb', 'כבש', 'טלה']),
 'goat': ('Chevreau', 'Goat', 'בשר עז', 'meat', 'meat', 4, ['chevreau', 'goat meat', 'בשר עז', 'גדי']),
 'sardines': ('Sardines', 'Sardines', 'סרדינים', 'grocery', None, 365, ['sardine', 'pilchard', 'סרדינים']),
 'anchovies': ('Anchois', 'Anchovies', 'אנשובי', 'grocery', None, 365, ['anchois', 'anchovy', 'אנשובי']),
 'cornmeal': ('Semoule de maïs', 'Cornmeal', 'קמח תירס', 'grocery', None, 365, ['semoule de mais', 'polenta', 'cornmeal', 'קמח תירס']),
 'semolina': ('Semoule fine', 'Semolina', 'סולת', 'grocery', None, 365, ['semoule fine', 'semolina', 'סולת']),
 'puff-pastry': ('Pâte feuilletée', 'Puff pastry', 'בצק עלים', 'bakery', None, 30, ['pate feuilletee', 'puff pastry', 'בצק עלים']),
 'shortcrust-pastry': ('Pâte brisée', 'Shortcrust pastry', 'בצק פריך', 'bakery', None, 30, ['pate brisee', 'pate sablee', 'shortcrust', 'בצק פריך']),
 'filo-pastry': ('Pâte filo', 'Filo pastry', 'בצק פילו', 'bakery', None, 30, ['pate filo', 'filo', 'phyllo', 'בצק פילו']),
 'walnuts': ('Noix', 'Walnuts', 'אגוזי מלך', 'grocery', None, 180, ['cerneaux de noix', 'walnut', 'אגוזי מלך']),
 'pine-nuts': ('Pignons de pin', 'Pine nuts', 'צנוברים', 'grocery', None, 180, ['pignons', 'pine nut', 'צנובר']),
 'pistachios': ('Pistaches', 'Pistachios', 'פיסטוקים', 'grocery', None, 180, ['pistache', 'pistachio', 'פיסטוק']),
 'peanuts': ('Cacahuètes', 'Peanuts', 'בוטנים', 'grocery', None, 180, ['cacahuete', 'arachide', 'peanuts', 'בוטנים']),
 'peanut-butter': ('Beurre de cacahuète', 'Peanut butter', 'חמאת בוטנים', 'grocery', None, 180, ['beurre de cacahuete', 'peanut butter', 'חמאת בוטנים']),
 'hazelnuts': ('Noisettes', 'Hazelnuts', 'אגוזי לוז', 'grocery', None, 180, ['noisette', 'hazelnut', 'אגוזי לוז']),
 'cashews': ('Noix de cajou', 'Cashews', 'קשיו', 'grocery', None, 180, ['noix de cajou', 'cashew', 'קשיו']),
 'pecans': ('Noix de pécan', 'Pecans', 'פקאנים', 'grocery', None, 180, ['noix de pecan', 'pecan', 'פקאן']),
 'coconut': ('Noix de coco râpée', 'Desiccated coconut', 'קוקוס טחון', 'grocery', None, 180, ['noix de coco rapee', 'coco rape', 'desiccated coconut', 'shredded coconut', 'קוקוס']),
 'sesame': ('Graines de sésame', 'Sesame seeds', 'שומשום', 'grocery', None, 365, ['graines de sesame', 'sesame seed', 'שומשום']),
 'sesame-oil': ('Huile de sésame', 'Sesame oil', 'שמן שומשום', 'grocery', None, 365, ['huile de sesame', 'sesame oil', 'שמן שומשום']),
 'poppy-seeds': ('Graines de pavot', 'Poppy seeds', 'פרג', 'grocery', None, 365, ['graines de pavot', 'poppy seed', 'פרג']),
 'dried-apricots': ('Abricots secs', 'Dried apricots', 'משמש מיובש', 'grocery', None, 180, ['abricots secs', 'dried apricot', 'משמש מיובש']),
 'prunes': ('Pruneaux', 'Prunes', 'שזיפים מיובשים', 'grocery', None, 180, ['pruneau', 'prunes', 'שזיפים מיובשים']),
 'dried-fruit': ('Fruits confits et secs', 'Mixed dried fruit', 'פירות יבשים', 'grocery', None, 180, ['fruits confits', 'melange de fruits secs', 'mixed peel', 'dried fruit', 'פירות יבשים']),
 'cocoa': ('Cacao en poudre', 'Cocoa powder', 'אבקת קקאו', 'grocery', None, 365, ['cacao en poudre', 'cacao', 'cocoa', 'קקאו']),
 'jam': ('Confiture', 'Jam', 'ריבה', 'grocery', None, 180, ['confiture', 'ריבה']),
 'golden-syrup': ('Mélasse ou sirop de sucre', 'Golden syrup or treacle', 'סירופ סוכר', 'grocery', None, 365, ['melasse', 'golden syrup', 'treacle', 'molasses', 'סירופ סוכר', 'מולסה']),
 'maple-syrup': ('Sirop d’érable', 'Maple syrup', 'סירופ מייפל', 'grocery', None, 365, ['sirop d erable', 'maple syrup', 'סירופ מייפל']),
 'biscuits': ('Biscuits secs', 'Digestive biscuits', 'ביסקוויטים', 'grocery', None, 180, ['biscuits secs', 'petit beurre', 'digestive', 'ביסקוויט']),
 'marzipan': ('Pâte d’amande', 'Marzipan', 'מרציפן', 'grocery', None, 180, ['pate d amande', 'marzipan', 'מרציפן']),
 'apricot': ('Abricots', 'Apricots', 'משמשים', 'fruit', None, 5, ['abricot', 'apricot', 'משמש']),
 'peach': ('Pêches', 'Peaches', 'אפרסקים', 'fruit', None, 5, ['peche', 'peach', 'אפרסק']),
 'blueberries': ('Myrtilles', 'Blueberries', 'אוכמניות', 'fruit', None, 5, ['myrtille', 'blueberr', 'אוכמניות']),
 'blackberries': ('Mûres', 'Blackberries', 'אוכמניות שחורות', 'fruit', None, 3, ['mures', 'blackberr', 'פטל שחור']),
 'raspberries': ('Framboises', 'Raspberries', 'פטל', 'fruit', None, 3, ['framboise', 'raspberr', 'פטל']),
 'cherries': ('Cerises', 'Cherries', 'דובדבנים', 'fruit', None, 5, ['cerise', 'cherry', 'cherries', 'דובדבן']),
 'rhubarb': ('Rhubarbe', 'Rhubarb', 'ריבס', 'veg', None, 7, ['rhubarbe', 'rhubarb', 'ריבס']),
 'plantain': ('Bananes plantain', 'Plantains', 'בננות פלנטיין', 'fruit', None, 7, ['banane plantain', 'plantain', 'פלנטיין']),
 'breadfruit': ('Fruit à pain', 'Breadfruit', 'פרי הלחם', 'veg', None, 5, ['fruit a pain', 'breadfruit', 'פרי הלחם']),
 'cassava': ('Manioc', 'Cassava', 'קסאווה', 'veg', None, 7, ['manioc', 'cassava', 'yuca', 'קסאווה']),
 'taro': ('Taro', 'Taro', 'טארו', 'veg', None, 7, ['taro', 'טארו', 'קולקס']),
 'papaya': ('Papaye', 'Papaya', 'פפאיה', 'fruit', None, 5, ['papaye', 'papaya', 'פפאיה']),
 'longan': ('Longanes', 'Longans', 'לונגן', 'fruit', None, 5, ['longane', 'longan', 'לונגן']),
 'fennel': ('Fenouil', 'Fennel', 'שומר', 'veg', None, 7, ['fenouil', 'fennel', 'שומר']),
 'shallot': ('Échalotes', 'Shallots', 'שאלוט', 'veg', None, 30, ['echalote', 'shallot', 'שאלוט']),
 'broad-beans': ('Fèves', 'Broad beans', 'פול', 'grocery', None, 365, ['feves', 'broad bean', 'fava', 'פול מצרי', 'פול ירוק']),
 'kidney-beans': ('Haricots rouges', 'Kidney beans', 'שעועית אדומה', 'grocery', None, 365, ['haricots rouges', 'kidney bean', 'שעועית אדומה']),
 'black-beans': ('Haricots noirs', 'Black beans', 'שעועית שחורה', 'grocery', None, 365, ['haricots noirs', 'black bean', 'שעועית שחורה']),
 'rocket': ('Roquette', 'Rocket', 'רוקט', 'veg', None, 4, ['roquette', 'rocket', 'arugula', 'רוקט', 'ארוגולה']),
 'bean-sprouts': ('Pousses de soja', 'Bean sprouts', 'נבטי סויה', 'veg', None, 3, ['pousses de soja', 'bean sprout', 'נבטים']),
 'asparagus': ('Asperges', 'Asparagus', 'אספרגוס', 'veg', None, 4, ['asperge', 'asparagus', 'אספרגוס']),
 'vine-leaves': ('Feuilles de vigne', 'Vine leaves', 'עלי גפן', 'grocery', None, 365, ['feuilles de vigne', 'vine leaves', 'grape leaves', 'עלי גפן']),
 'sauerkraut': ('Choucroute', 'Sauerkraut', 'כרוב כבוש', 'grocery', None, 60, ['choucroute', 'sauerkraut', 'כרוב כבוש']),
 'palm-hearts': ('Cœurs de palmier', 'Hearts of palm', 'לבבות דקל', 'grocery', None, 365, ['coeurs de palmier', 'heart of palm', 'palm hearts', 'לבבות דקל']),
 'capers': ('Câpres', 'Capers', 'צלפים', 'grocery', None, 365, ['capres', 'capers', 'צלפים']),
 'lemongrass': ('Citronnelle', 'Lemongrass', 'עשב לימון', 'herbs', None, 10, ['citronnelle', 'lemongrass', 'עשב לימון']),
 'chives': ('Ciboulette', 'Chives', 'עירית', 'herbs', None, 5, ['ciboulette', 'chives', 'עירית']),
 'noodles': ('Nouilles', 'Noodles', 'אטריות', 'grocery', None, 365, ['nouilles', 'noodles', 'אטריות']),
 'buckwheat': ('Sarrasin', 'Buckwheat', 'כוסמת', 'grocery', None, 365, ['sarrasin', 'kasha', 'buckwheat', 'כוסמת']),
 'freekeh': ('Frikeh', 'Freekeh', 'פריקה', 'grocery', None, 365, ['frikeh', 'freekeh', 'פריקה']),
 'tapioca': ('Tapioca', 'Tapioca', 'טפיוקה', 'grocery', None, 365, ['tapioca', 'טפיוקה']),
 'rye-flour': ('Farine de seigle', 'Rye flour', 'קמח שיפון', 'grocery', None, 365, ['farine de seigle', 'rye flour', 'קמח שיפון']),
 'mung-beans': ('Haricots mungo', 'Mung beans', 'מש', 'grocery', None, 365, ['haricots mungo', 'mung bean', 'שעועית מש']),
 'pretzels': ('Bretzels', 'Pretzels', 'בייגלה', 'grocery', None, 180, ['bretzel', 'pretzel', 'בייגלה']),
 'mayonnaise': ('Mayonnaise', 'Mayonnaise', 'מיונז', 'grocery', None, 90, ['mayonnaise', 'mayo', 'מיונז']),
 'ketchup': ('Ketchup', 'Ketchup', 'קטשופ', 'grocery', None, 180, ['ketchup', 'קטשופ']),
 'wine': ('Vin', 'Wine', 'יין', 'grocery', None, 365, ['vin blanc', 'vin rouge', 'xeres', 'wine', 'sherry', 'יין']),
}
